In [3]:
# set base path to the directory containing the csv files of the dataset
dataset_base_path = r'/Users/kripik123/Documents/dataset/CIC_IDS_2018/'

#Removing invalid rows
import numpy as np
import pandas as pd
import os

file_path = os.path.join(dataset_base_path, 'Friday-02-03-2018_TrafficForML_CICFlowMeter.csv')

df = pd.read_csv(file_path)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 80 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   Dst Port           1048575 non-null  int64
 1   Protocol           1048575 non-null  int64
 2   Timestamp          1048575 non-null  object
 3   Flow Duration      1048575 non-null  int64
 4   Tot Fwd Pkts       1048575 non-null  int64
 5   Tot Bwd Pkts       1048575 non-null  int64
 6   TotLen Fwd Pkts    1048575 non-null  int64
 7   TotLen Bwd Pkts    1048575 non-null  float64
 8   Fwd Pkt Len Max    1048575 non-null  int64
 9   Fwd Pkt Len Min    1048575 non-null  int64
 10  Fwd Pkt Len Mean   1048575 non-null  float64
 11  Fwd Pkt Len Std    1048575 non-null  float64
 12  Bwd Pkt Len Max    1048575 non-null  int64
 13  Bwd Pkt Len Min    1048575 non-null  int64
 14  Bwd Pkt Len Mean   1048575 non-null  float64
 15  Bwd Pkt Len Std    1048575 non-null  float64
 16  Flow Byts/s        1046017 non-null  float64
 17  Flow Pkts/s        1048575 non-null  float64
 18  Flow IAT Mean      1048575 non-null  float64
 19  Flow IAT Std       1048575 non-null  float64
 20  Flow IAT Max       1048575 non-null  float64
 21  Flow IAT Min       1048575 non-null  float64
 22  Fwd IAT Tot        1048575 non-null  float64
 23  Fwd IAT Mean       1048575 non-null  float64
 24  Fwd IAT Std        1048575 non-null  float64
 25  Fwd IAT Max        1048575 non-null  float64
 26  Fwd IAT Min        1048575 non-null  float64
 27  Bwd IAT Tot        1048575 non-null  float64
 28  Bwd IAT Mean       1048575 non-null  float64
 29  Bwd IAT Std        1048575 non-null  float64
 30  Bwd IAT Max        1048575 non-null  float64
 31  Bwd IAT Min        1048575 non-null  float64
 32  Fwd PSH Flags      1048575 non-null  int64
 33  Bwd PSH Flags      1048575 non-null  int64
 34  Fwd URG Flags      1048575 non-null  int64
 35  Bwd URG Flags      1048575 non-null  int64
 36  Fwd Header Len     1048575 non-null  int64
 37  Bwd Header Len     1048575 non-null  int64
 38  Fwd Pkts/s         1048575 non-null  float64
 39  Bwd Pkts/s         1048575 non-null  float64
 40  Pkt Len Min        1048575 non-null  int64
 41  Pkt Len Max        1048575 non-null  int64
 42  Pkt Len Mean       1048575 non-null  float64
 43  Pkt Len Std        1048575 non-null  float64
 44  Pkt Len Var        1048575 non-null  float64
 45  FIN Flag Cnt       1048575 non-null  int64
 46  SYN Flag Cnt       1048575 non-null  int64
 47  RST Flag Cnt       1048575 non-null  int64
 48  PSH Flag Cnt       1048575 non-null  int64
 49  ACK Flag Cnt       1048575 non-null  int64
 50  URG Flag Cnt       1048575 non-null  int64
 51  CWE Flag Count     1048575 non-null  int64
 52  ECE Flag Cnt       1048575 non-null  int64
 53  Down/Up Ratio      1048575 non-null  int64
 54  Pkt Size Avg       1048575 non-null  float64
 55  Fwd Seg Size Avg   1048575 non-null  float64
 56  Bwd Seg Size Avg   1048575 non-null  float64
 57  Fwd Byts/b Avg     1048575 non-null  int64
 58  Fwd Pkts/b Avg     1048575 non-null  int64
 59  Fwd Blk Rate Avg   1048575 non-null  int64
 60  Bwd Byts/b Avg     1048575 non-null  int64
 61  Bwd Pkts/b Avg     1048575 non-null  int64
 62  Bwd Blk Rate Avg   1048575 non-null  int64
 63  Subflow Fwd Pkts   1048575 non-null  int64
 64  Subflow Fwd Byts   1048575 non-null  int64
 65  Subflow Bwd Pkts   1048575 non-null  int64
 66  Subflow Bwd Byts   1048575 non-null  int64
 67  Init Fwd Win Byts  1048575 non-null  int64
 68  Init Bwd Win Byts  1048575 non-null  int64
 69  Fwd Act Data Pkts  1048575 non-null  int64
 70  Fwd Seg Size Min   1048575 non-null  int64
 71  Active Mean        1048575 non-null  float64
 72  Active Std         1048575 non-null  float64
 73  Active Max         1048575 non-null  float64
 74  Active Min         1048575 non-null  float64
 75  Idle Mean          1048575 non-null  float64
 76  Idle Std           1048575 non-null  float64
 77  Idle Max           1048575 non-null  float64
 78  Idle Min           1048575 non-null  float64
 79  Label              1048575 non-null  object
dtypes: float64(37), int64(41), object(2)
memory usage: 640.0+ MB

In [13]:
df.head(10)

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
0,443,6,02/03/2018 08:47:38,141385,9,7,553,3773.0,202,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1,49684,6,02/03/2018 08:47:38,281,2,1,38,0.0,38,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
2,443,6,02/03/2018 08:47:40,279824,11,15,1086,10527.0,385,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
3,443,6,02/03/2018 08:47:40,132,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
4,443,6,02/03/2018 08:47:41,274016,9,13,1285,6141.0,517,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
5,443,6,02/03/2018 08:47:41,250,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
6,80,6,02/03/2018 08:47:41,5964033,3,1,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
7,49690,6,02/03/2018 08:47:46,144,2,0,0,0.0,0,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
8,443,6,02/03/2018 08:48:17,90828,8,8,1748,3898.0,1078,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
9,443,6,02/03/2018 08:48:17,152,3,0,31,0.0,31,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [17]:
df.tail(5)

,Dst Port,Protocol,Timestamp,Flow Duration,Tot Fwd Pkts,Tot Bwd Pkts,TotLen Fwd Pkts,TotLen Bwd Pkts,Fwd Pkt Len Max,Fwd Pkt Len Min,...,Fwd Seg Size Min,Active Mean,Active Std,Active Max,Active Min,Idle Mean,Idle Std,Idle Max,Idle Min,Label
1048570,3389,6,02/03/2018 02:08:18,3982183,14,8,1442,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048571,3389,6,02/03/2018 02:08:22,3802316,14,8,1440,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048572,3389,6,02/03/2018 02:08:25,4004239,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048573,3389,6,02/03/2018 02:08:29,3998435,14,8,1459,1731.0,741,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign
1048574,3389,6,02/03/2018 02:08:33,3972651,14,8,1439,1731.0,725,0,...,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Benign

In [4]:
df['Protocol'].value_counts()

6     832492
17    202701
0      13382
Name: Protocol, dtype: int64

In [5]:
df['FIN Flag Cnt'].value_counts()

0    1044701
1       3874
Name: FIN Flag Cnt, dtype: int64

In [11]:
##df = df[~df['Dst Port'].str.contains('Dst Port', na=False)]

In [7]:
import re

tmp_path = os.path.join(dataset_base_path, 'tmp')

if not os.path.exists(tmp_path):
    os.mkdir(tmp_path)

column_name_regex = re.compile(r"\W", re.IGNORECASE)
df.columns = [column_name_regex.sub('_', c.lower()) for c in df.columns]

tmp_file_path = os.path.join(tmp_path, 'Friday-02-03-2018_TrafficForML_CICFlowMeter_duplicate_headers_removed.csv')

df.to_csv(tmp_file_path)

In [8]:
types = {
    'dst_port': 'uint32',
    'protocol': 'uint8',
    'timestamp': 'object',
    'flow_duration': 'int64',
    'tot_fwd_pkts': 'uint32',
    'tot_bwd_pkts': 'uint32',
    'totlen_fwd_pkts': 'uint32',
    'totlen_bwd_pkts': 'uint32',
    'fwd_pkt_len_max': 'uint16',
    'fwd_pkt_len_min': 'uint16',
    'fwd_pkt_len_mean': 'float32',
    'fwd_pkt_len_std': 'float32',
    'bwd_pkt_len_max': 'uint16',
    'bwd_pkt_len_min': 'uint16',
    'bwd_pkt_len_mean': 'float32',
    'bwd_pkt_len_std': 'float32',
    'flow_byts_s': 'float64',
    'flow_pkts_s': 'float64',
    'flow_iat_mean': 'float32',
    'flow_iat_std': 'float32',
    'flow_iat_max': 'int64',
    'flow_iat_min': 'int64',
    'fwd_iat_tot': 'int64',
    'fwd_iat_mean': 'float32',
    'fwd_iat_std': 'float32',
    'fwd_iat_max': 'int64',
    'fwd_iat_min': 'int64',
    'bwd_iat_tot': 'uint32',
    'bwd_iat_mean': 'float32',
    'bwd_iat_std': 'float32',
    'bwd_iat_max': 'uint32',
    'bwd_iat_min': 'uint32',
    'fwd_psh_flags': 'uint8',
    'bwd_psh_flags': 'uint8',
    'fwd_urg_flags': 'uint8',
    'bwd_urg_flags': 'uint8',
    'fwd_header_len': 'uint32',
    'bwd_header_len': 'uint32',
    'flow_byts_s': 'float32',
    'bwd_pkts_s': 'float32',
    'pkt_len_min': 'uint16',
    'pkt_len_max': 'uint16',
    'pkt_len_mean': 'float32',
    'pkt_len_std': 'float32',
    'pkt_len_var': 'float32',
    'fin_flag_cnt': 'uint8',
    'syn_flag_cnt': 'uint8',
    'rst_flag_cnt': 'uint8',
    'psh_flag_cnt': 'uint8',
    'ack_flag_cnt': 'uint8',
    'urg_flag_cnt': 'uint8',
    'cwe_flag_count': 'uint8',
    'ece_flag_cnt': 'uint8',
    'down_up_ratio': 'uint16',
    'pkt_size_avg': 'float32',
    'fwd_seg_size_avg': 'float32',
    'bwd_seg_size_avg': 'float32',
    'fwd_byts_b_avg': 'uint8',
    'fwd_pkts_b_avg': 'uint8',
    'fwd_blk_rate_avg': 'uint8',
    'bwd_byts_b_avg': 'uint8',
    'bwd_pkts_b_avg': 'uint8',
    'bwd_blk_rate_avg': 'uint8',
    'subflow_fwd_pkts': 'uint32',
    'subflow_fwd_byts': 'uint32',
    'subflow_bwd_pkts': 'uint32',
    'subflow_bwd_byts': 'uint32',
    'init_fwd_win_byts': 'int32',
    'init_bwd_win_byts': 'int32',
    'fwd_act_data_pkts': 'uint32',
    'fwd_seg_size_min': 'uint8',
    'active_mean': 'float32',
    'active_std': 'float32',
    'active_max': 'uint32',
    'active_min': 'uint32',
    'idle_mean': 'float32',
    'idle_std': 'float32',
    'idle_max': 'uint64',
    'idle_min': 'uint64',
    'label': 'category'
}

In [9]:
df = pd.read_csv(tmp_file_path, dtype=types)

In [10]:
df = pd.read_csv(tmp_file_path)

df_infinity_fixed = df.replace('Infinity', 'inf')

tmp_file_path_inf = os.path.join(tmp_path, 'Friday-02-03-2018_TrafficForML_CICFlowMeter_infinity_fixed.csv')

df_infinity_fixed.to_csv(tmp_file_path_inf)

In [12]:
df = pd.read_csv(tmp_file_path_inf, dtype=types)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048575 entries, 0 to 1048574
Data columns (total 82 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   Unnamed: 0         1048575 non-null  int64
 1   Unnamed: 0.1       1048575 non-null  int64
 2   dst_port           1048575 non-null  uint32
 3   protocol           1048575 non-null  uint8
 4   timestamp          1048575 non-null  object
 5   flow_duration      1048575 non-null  int64
 6   tot_fwd_pkts       1048575 non-null  uint32
 7   tot_bwd_pkts       1048575 non-null  uint32
 8   totlen_fwd_pkts    1048575 non-null  uint32
 9   totlen_bwd_pkts    1048575 non-null  uint32
 10  fwd_pkt_len_max    1048575 non-null  uint16
 11  fwd_pkt_len_min    1048575 non-null  uint16
 12  fwd_pkt_len_mean   1048575 non-null  float32
 13  fwd_pkt_len_std    1048575 non-null  float32
 14  bwd_pkt_len_max    1048575 non-null  uint16
 15  bwd_pkt_len_min    1048575 non-null  uint16
 16  bwd_pkt_len_mean   1048575 non-null  float32
 17  bwd_pkt_len_std    1048575 non-null  float32
 18  flow_byts_s        1046017 non-null  float32
 19  flow_pkts_s        1048575 non-null  float64
 20  flow_iat_mean      1048575 non-null  float32
 21  flow_iat_std       1048575 non-null  float32
 22  flow_iat_max       1048575 non-null  int64
 23  flow_iat_min       1048575 non-null  int64
 24  fwd_iat_tot        1048575 non-null  int64
 25  fwd_iat_mean       1048575 non-null  float32
 26  fwd_iat_std        1048575 non-null  float32
 27  fwd_iat_max        1048575 non-null  int64
 28  fwd_iat_min        1048575 non-null  int64
 29  bwd_iat_tot        1048575 non-null  uint32
 30  bwd_iat_mean       1048575 non-null  float32
 31  bwd_iat_std        1048575 non-null  float32
 32  bwd_iat_max        1048575 non-null  uint32
 33  bwd_iat_min        1048575 non-null  uint32
 34  fwd_psh_flags      1048575 non-null  uint8
 35  bwd_psh_flags      1048575 non-null  uint8
 36  fwd_urg_flags      1048575 non-null  uint8
 37  bwd_urg_flags      1048575 non-null  uint8
 38  fwd_header_len     1048575 non-null  uint32
 39  bwd_header_len     1048575 non-null  uint32
 40  fwd_pkts_s         1048575 non-null  float64
 41  bwd_pkts_s         1048575 non-null  float32
 42  pkt_len_min        1048575 non-null  uint16
 43  pkt_len_max        1048575 non-null  uint16
 44  pkt_len_mean       1048575 non-null  float32
 45  pkt_len_std        1048575 non-null  float32
 46  pkt_len_var        1048575 non-null  float32
 47  fin_flag_cnt       1048575 non-null  uint8
 48  syn_flag_cnt       1048575 non-null  uint8
 49  rst_flag_cnt       1048575 non-null  uint8
 50  psh_flag_cnt       1048575 non-null  uint8
 51  ack_flag_cnt       1048575 non-null  uint8
 52  urg_flag_cnt       1048575 non-null  uint8
 53  cwe_flag_count     1048575 non-null  uint8
 54  ece_flag_cnt       1048575 non-null  uint8
 55  down_up_ratio      1048575 non-null  uint16
 56  pkt_size_avg       1048575 non-null  float32
 57  fwd_seg_size_avg   1048575 non-null  float32
 58  bwd_seg_size_avg   1048575 non-null  float32
 59  fwd_byts_b_avg     1048575 non-null  uint8
 60  fwd_pkts_b_avg     1048575 non-null  uint8
 61  fwd_blk_rate_avg   1048575 non-null  uint8
 62  bwd_byts_b_avg     1048575 non-null  uint8
 63  bwd_pkts_b_avg     1048575 non-null  uint8
 64  bwd_blk_rate_avg   1048575 non-null  uint8
 65  subflow_fwd_pkts   1048575 non-null  uint32
 66  subflow_fwd_byts   1048575 non-null  uint32
 67  subflow_bwd_pkts   1048575 non-null  uint32
 68  subflow_bwd_byts   1048575 non-null  uint32
 69  init_fwd_win_byts  1048575 non-null  int32
 70  init_bwd_win_byts  1048575 non-null  int32
 71  fwd_act_data_pkts  1048575 non-null  uint32
 72  fwd_seg_size_min   1048575 non-null  uint8
 73  active_mean        1048575 non-null  float32
 74  active_std         1048575 non-null  float32
 75  active_max         1048575 non-null  uint32
 76  active_min         1048575 non-null  uint32
 77  idle_mean          1048575 non-null  float32
 78  idle_std           1048575 non-null  float32
 79  idle_max           1048575 non-null  uint64
 80  idle_min           1048575 non-null  uint64
 81  label              1048575 non-null  category
dtypes: category(1), float32(22), float64(2), int32(2), int64(8), object(1), uint16(7), uint32(17), uint64(2), uint8(20)
memory usage: 303.0+ MB

In [14]:
print(f"Infinity values of flow_byts_s: {df[df['flow_byts_s'] == np.inf]['dst_port'].count()}")
print(f"Null values of flow_byts_s: {df[df['flow_byts_s'].isnull()]['dst_port'].count()}")

Infinity values of flow_byts_s: 1492
Null values of flow_byts_s: 2558